# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='neighbors',
            field=models.ManyToManyField(related_name='_room_neighbors_+', to='maze.Room'),
        ),
        migrations.AddField(
            model_name='roomitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maze.Item'),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maze.Room'),
        ),
    ]
